### ISSUE TITLE
smc_rna_submit.py needs to be updated to use hints

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/SMC-RNA-Challenge#16]
The manual has been updated to advice users to use the `hints` section of the CWL document for define where input files can be found. 
https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/script/smc_rna_submit.py#L90 will need to be updated to check for this new inputs format

Example hints:

```
cwlVersion: "draft-3"

hints:
  - class: synData
    input: index
    entity: syn5909383

inputs: 
  - id: index
    type: File
  - id: TUMOR_FASTQ_1
    type: File
  - id: TUMOR_FASTQ_2
    type: File
```
