### ISSUE TITLE
Improve dream_runner inputs mapping

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/SMC-RNA-Challenge#20]
Currently the dream_runner input mapping is hard-coded to the example workflows and will break on user supplied code. 
On line https://github.com/Sage-Bionetworks/SMC-RNA-Challenge/blob/master/script/dream_runner.py#L49 it hard codes in the input `"--index", index_path`, but index is specific to the provided examples. If the users provides a `blacklist` input, dreamrunner will break on attempting to run the workflow. 

Given an example workflow:

```
cwlVersion: "draft-3"
hints:
  - class: synData
    input: index
    entity: syn5909383
inputs: 
  - id: index
    type: File    
  - id: TUMOR_FASTQ_1
    type: File
  - id: TUMOR_FASTQ_2
    type: File
```

The behavior should be:
1. Scan the `hints` stanza looking for items of `synData` class, using the `id` field to determine the name and the `entity` field to identify which element in synapse needs to be downloaded
2. Download the required elements and collecting the paths
3. Construct the the inputs array in the `call_workflow` function based on the `id` fields and the collected paths
